name: Frontend CI (Next.js)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-practice-fe

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check ESLint
        run: pnpm lint

      - name: Check Prettier
        run: pnpm format:check

      - name: Build project
        run: pnpm build
